### ISSUE TITLE
Duplicate commons versions

### ISSUE THREAD

**Issue by tylergraf** [splitio/react-client#114]
Is there a reason you're hard pinned to splitio-commons? https://github.com/splitio/react-client/blob/master/package.json#L65 I'm seeing a duplicate version being pulled into my app.

**Comment by chillaq** [comment]
Hi @tylergraf , there should be only one version since no other splitio package exist in the "dependencies" section. We do have another splitio package in the DevDependencies, which might use different version of split-commons, but that won't be deployed into prod.

Do you have any errors or issues in the dev environment?

**Comment by chillaq** [comment]
Hi @tylergraf, 

I'm following up on this issue. Do you still require any assistance?

Thanks,
Bilal

**Comment by EmilianoSanchez** [comment]
FYI, we have released [React SDK v1.8.1](https://www.npmjs.com/package/@splitsoftware/splitio-react) and finally tide up its dependencies and devDependencies: as you can check in https://github.com/splitio/react-client/blob/master/package.json#L65 we replaced `@splitsoftware/splitio-commons` with `@splitsoftware/splitio`

We had to add `@splitsoftware/splitio-commons` as a (runtime) dependency, instead of `@splitsoftware/splitio` to avoid in issue when running the library in NodeJS, for example, for [tests with Jest](https://github.com/splitio/react-client/issues/34). But now we were able to rollback that change.
