### ISSUE TITLE
Localhost mode always evaluating treatment as control

### ISSUE THREAD

**Issue by sharmabhawna** [splitio/react-client#124]
Hi, we are using react-client while writing tests we realised for localhost mode even after split sdk is ready treatment is always getting evaluated as "control".
Here's the link of code sandbox: https://codesandbox.io/s/splitio-react-localhost-mode-6x4wjq?file=/src/App.js
The same can be seen in the logs as well as the render of the app.

**Comment by agustinona** [comment]
Hi @sharmabhawna ,

It seems in your code you are using an unsupported **features** object structure:
`features: {
      feature_key: {
        treatments: [
          {
            name: "on",
            description: "feature enabled",
            keys: ["react-user"]
          },
          {
            name: "off",
            description: "feature disabled"
          }
        ]
      }
    }`

So the SDK is failing to properly parse the feature and returning the control treatment for it instead.

May I ask where did you source this code from? In order to run the SDK in localhost mode, please refer to our documentation: https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#localhost-mode.

Using the object structure documented there I can get the feature to show as expected:

`features: {
      feature_key: { treatment: "on" }
    }`

**Comment by sharmabhawna** [comment]
Thanks @agustinona for the info.
I would like to understand with the new structure is there a way I can also provide the individual targets and targeting rules configuration.

**Comment by agustinona** [comment]
@sharmabhawna,

You can pass the dynamic configuration for a particular treatment in the 'config' field for the split:
`features: {
    'reporting_v2': 'on', // example with just a string value for the treatment
    'billing_updates': { treatment: 'visa', config: '{ "color": "blue" }' }, //example of a defined config 
    'show_status_bar': { treatment: 'off', config: null } // example of a null config
  }`

Individual targets in the localhost mode split definitions are not supported for our JS SDK in the client side. Usually this would not be required though, since in the client side you'd be evaluating a single key for any given split. In order to change the key you'd be reinstantiating the factory at which point you can also change the **features** object in the config to serve a different treatment for that split. May I ask what's your use case for individual targets in localhost mode using our React SDK?

Advanced targeting rules configurations, such as custom attribute targeting and percentage rollouts, are not supported in localhost mode either.

**Comment by mmelograno** [comment]
Proceeding to close the ticket since it was solved for another communication channel.
