### ISSUE TITLE
Issue with SplitClient undefined attributes

### ISSUE THREAD

**Issue by dainius-tamosiunas-tg** [splitio/react-client#143]
Hi,

I have a question related to `SplitClient` and `undefined` attributes. Basically if any of the attributes is `undefined`, attributes are not being passed at all. Is this expected or bug?

e.g. this works fine(attribute `someAttribute` is passed):
```
                <SplitClient
                    splitKey="someKey"
                    attributes={{
                        someAttribute: 'test'
                    }}
                >
```

and this doesn't work, no attributes are being passed at all:
```
                <SplitClient
                    splitKey="someKey"
                    attributes={{
                        someAttribute: 'test'
                        someAttribute2: undefined,
                    }}
                >
```

**Comment by dmurphy4040** [comment]
If you don't pass an attribute then we don't evaluate that as part of the rollout plan.  If you have attributes in your rollout plan then passing nothing just means that you don't match any of the attributes you've set in the rules that use attributes and it will fall to the next rule, ultimately to the final ELSE.
dave

**Comment by agustinona** [comment]
@dainius-tamosiunas-tg 

Thanks for this report! This is not intended behavior. We were able to reproduce the issue and our team will be looking into it. Note that this only affects the [attribute binding API](https://help.split.io/hc/en-us/articles/360038825091-React-SDK#binding-attributes-to-the-client), and is not an issue when passing attributes through the SplitTreatments component or withSplitTreatments HOC, or useTreatments hook.

**Comment by agustinona** [comment]
@dainius-tamosiunas-tg 

Let me correct myself on this. This is indeed the intended behavior for the attribute binding API. There is a slight difference with the way attributes are handled in the SplitTreatments component or useTreatments hook, where you can pass undefined attributes.

The SDK does not allow you to permanently bind an attribute as undefined, since it serves no purpose and would most likely be unintended. The way the attribute binding API is designed is it performs a type validation for the attributes provided and returns a false value if an issue is detected, in which case no attributes are bound. For more details on this you can refer to our [Javascript SDK](https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#binding-attributes-to-the-client) which is what the react SDK runs under the hood.

**Comment by dainius-tamosiunas-tg** [comment]
@agustinona well, it's a bit confusing as behaviours are different for some reason for treatments and clients. and that `undefined` could be intended as well. e.g. when some parameters are known and hardcoded and some are not until user logs in to the page(e.g. user country/nationality etc.). in that case, when user is not logged in, we lose all attributes instead of the ones from logged in user data, which is a bit confusing behaviour, don't you think?

**Comment by agustinona** [comment]
@dainius-tamosiunas-tg I understand the concern here. I'm submitting this as an RFE on your behalf for consideration by our team. 

In the immediate term I suggest you sanitize the attributes object by removing all undefined keys from it before passing it to the SplitClient component, which will prevent any unexpected behavior.
