### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by BigGillyStyle** [splitio/react-client#176]
We're looking to use Split.io in React/PNPM workspace. PNPM is reporting a circular dependency:

1. https://github.com/splitio/react-client/blob/master/src/utils.ts imports items from `./constants.js`
2. https://github.com/splitio/react-client/blob/master/src/constants.ts imports an item from `./utils.js`

**Comment by EmilianoSanchez** [comment]
Thanks @BigGillyStyle for sharing. 

I just did the refactor, but will be included in the next release. Right now, I would suggest ignoring the report/warning from PNPM.

**Comment by EmilianoSanchez** [comment]
Hi @BigGillyStyle 

A new version of the React SDK (v1.11.0) was released, which includes the refactor for the circular dependency.

When you decide to upgrade, consider replacing the now deprecated `SplitFactory` component with the new `SplitFactoryProvider` component introduced in version 1.11.0. This is a drop-in replacement of `SplitFactory` component that properly handles side-effects in React component's lifecycle. 

FYI, we decided to provide a new component rather than fixing the deprecated one, because it implies a few breaking changes that will likely not affect you: (1) it requires React v16.8.0 or above, while `SplitFactory` requires React v16.3.0 or above, and (2) if you use `factory` and `client` properties from the context (e.g., `const { factory, client } = useContext(SplitContext)` or `<SplitFactoryProvider config={myConfig} >{({ factory, client, ...}) => {...`), which are not recommended to use directly since there are better options like the available library hooks, they will be `null` on the first render. 

`SplitFactory` component will be removed in next major version.

I will be closing the issue for now.
