### ISSUE TITLE
Throw an error if using context outside of a <SplitFactoryProvider>

### ISSUE THREAD

**Issue by murtinha** [splitio/react-client#222]
So flags were not working for me for a while because `isReady` was always false due to its usage outside of a SplitFactoryProvider. 

Shouldnt it throws? Or is there a way I can do that to prevent this from happening again?

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Update the useSplitContext hook in SplitContext.ts to throw an error when the context is undefined, indicating it's being used outside of a SplitFactoryProvider. This change will help prevent silent failures and make it easier to catch misuse of Split-related hooks.

You can review changes in this commit: https://github.com/mnmnk43434/splitio-react-client-222/commit/30a9955628844a9fe85a2a16b0675b20dd2a0a54.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by EmilianoSanchez** [comment]
Hi @murtinha , 

Since version 2.0.0 of the React SDK we changed the behavior as you mentioned: if you use the library modules, for example `useSplitTreatments`, outside the `SplitFactoryProvider` component, an exception is thrown. 

This is better explained in the CHANGELOG entry [here](https://github.com/splitio/react-client/blob/2.0.0/CHANGES.txt#L9).
