### ISSUE TITLE
Destroying split clients on `key` changes.

### ISSUE THREAD

**Issue by rvonzimr** [splitio/react-client#89]
Hello!
So I have an "advanced use case" according to your docs, we currently split traffic in a few ways depending on the feature we're testing out. This could be scoped to a `user`, a set of users within a `team`, etc.

This has required me to implement a custom `useTreatment` hook which uses `useSplitClient` under the hood. However, I'm running into a few issues with my implementation:
- when a user signs out, and signs into a separate account I now have two split clients, with no easy way to destroy the previous split client. This leads to `eventEmitter` warnings.
- If a user switches teams, again we have the same issue.

It looks like the `destroy` method on a client _also_ destroys the factory instance. [This doesn't sound good](https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#shutdown)

There's also no way to update the `key` prop either, as far as I can tell. What's the recommend way of doing this within the react library?

**Comment by chillaq** [comment]
Hi @rvonzimr , you are correct, you cannot update the key after the client is created, and calling destroy will disable the parent factory.

There is no issue creating multiple clients, as long as they don't grow too big, the user might login/logout once or twice during the same session, probably not more.

Did you try to use "delete client" Javascript command? That should release it from memory.

**Comment by rvonzimr** [comment]
@chillaq this would delete the reference I have to the client in my hook, but this isn't going to remove it from the factory instance will it?

**Comment by chillaq** [comment]
@rvonzimr if the client instance is deleted, its gone from the factory instance.

**Comment by rvonzimr** [comment]
Even if this did work, using `delete` isn't exactly a great solution here.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete#description

Why isn't there a way to remove a split client by key from the factory instance?

**Comment by chillaq** [comment]
Hi @rvonzimr , I understand your concern, I think we designed this function based on having one user in general interacting with the client SDKs (mobile and web), which is why it is confusing.
Also keep in mind, no object is really destroyed from memory when you call client.destroy(), the factory and client objects are still alive in memory, but the background threads are stopped.

**Comment by jamesarosen** [comment]
I think we've run into the same issue. We have some flags that are meaningful to anonymous users (like a maximum number of retries or which sign-in UI to use) and others that only make sense to signed-in users. 

I tried doing this:

```ts
function MySplitProvider({ children }) {
  const { user } = useAuthenticatedUser();

  const config = useMemo<SplitIO.IBrowserSettings>(
    () => ({
      core: {
        authorizationKey: SPLIT_AUTHORIZATION_KEY,
        key: user?.email ?? generateAnAnonymousID(),
      },
    }),
    [user],
  );

  return <SplitFactory config={config}>{children}</SplitFactory>
}
```

But when the user completes the authentication flow and `useAuthenticatedUser` returns a new value, Split continues to use the anonymous `key`.

**Comment by EmilianoSanchez** [comment]
Hi @jamesarosen , 

Unfortunately, as explained [here](https://github.com/splitio/react-client/issues/148#issuecomment-1646253457), you cannot update the underlying SDK config (and SDK factory) inside the `SplitFactory` provider component. The config cannot be changed during the component lifecycle, even if the component is updated with a different config prop, as I can see you are doing.

Yes, this is an anti-intuitive behaviour of the `SplitFactory` provider, but we cannot change it without doing a breaking change.

So, at the moment I would suggest you using one of the following approaches:

1- Using the `SplitClient` component to update the user (client) in the context of your wrapped children:

```
function MySplitProvider({ children }) {
  const { user } = useAuthenticatedUser();

  const config = {
      core: {
        authorizationKey: SPLIT_AUTHORIZATION_KEY,
        key: generateAnAnonymousID(),
      },
  };

  return (
    <SplitFactory config={config}>
      <SplitClient splitKey={user && user.email} >
        {children}
      </SplitClient>
    </SplitFactory>
  )
}
```

2- Use the `useSplitClient` or `useSplitTreatments` hooks, to retrieve the client or treatments for the provided `user`:

```
function MySplitProvider({ children }) {
  const config = {
      core: {
        authorizationKey: SPLIT_AUTHORIZATION_KEY,
        key: generateAnAnonymousID(),
      },
  };

  return (
    <SplitFactory config={config}>{children}</SplitFactory>
  )
}

// Example of "children" implementation:
function MyChildrenComponent () {
  const { user } = useAuthenticatedUser();
  
  const { treatments, isReady } = useSplitTreatments({ splitKey: user && user.email, names: ['my_feature_flag'] };
  
  return user ? 
    isReady ?  
      treatments['my_feature_flag'].treatment === 'on' ? 
        <OnVariant> : 
        <OffVariant> :
      <Loading> : // user is authenticated, but SDK client is not ready yet
    <Login> // user === undefined -> it's not logged in, `treatments` are for `anonymousId`
}
```
 
Both `SplitClient`, `useSplitClient` and `useSplitTreatments` accept an optional `splitKey` property. If it is not provided (i.e., undefined), they will use the available SDK client at the context, in this case, the one with key at `config.core.key`.

Note that the `useSplitClient` and `useSplitTreatments` hooks are available in the latest versions of the React SDK (+1.10.0), and should be used instead of the now deprecated `useClient` and `useTreatments` hooks.

**Comment by jamesarosen** [comment]
> Use the SplitClient component to update the user (client) in the context of your wrapped children. Unlike SplitFactory, the SplitClient component does update if the splitKey prop is changed

This is super helpful. Thank you so much!
